### ISSUE TITLE
Play/pause not working on Firefox 67 on Windows 10

### ISSUE THREAD

**Issue by CanzonELaLa** [carlin-q-scott/browser-media-players#29] opened 2019-05-31 22:37 UTC
Hi there!
I just moved from Chrome to FF after hearing about Google's new adblocker policies.
Anyway, When trying to control Youtube using my keyboard while the tab is focused, nothing happens.

Also, do you have any prospects on when the FF specific limitations might be lifted? Are they considered bugs?

Cheers, Canzone

**Comment by carlin-q-scott** [comment] 2019-06-13 00:19
@CanzonELaLa Could you try reloading the page? Youtube support is a tad buggy due to youtube having lots of subpages and sometimes multiple video players open.

**Comment by carlin-q-scott** [comment] 2019-10-25 17:12
This is a duplicate of #16

**Closed by carlin-q-scott** 2019-10-25 17:12 UTC
Labels: duplicate
